version: '3.8'  # Specify the version of Docker Compose

services:
  backend:
    container_name: demo-backend:latest  # Meaningful name for the backend container
    build:
      context: ./backend-express  # Path to the backend Dockerfile
    ports:
      - "3001:3000"  # Map container's port 3000 to host's port 3001 (to avoid conflict with frontend)
    labels:
      - "app=backend-express"
    environment:
      - NODE_ENV=production  # Example environment variable
    networks:
      - app-network  # Use a shared network with the frontend service

  frontend:
    container_name: demo-frontend:latest  # Meaningful name for the frontend container
    build:
      context: ./frontend  # Path to the frontend Dockerfile
    ports:
      - "3000:3000"  # Map container's port 3000 to host's port 3000
    labels:
      - "app=frontend-nextjs"
    depends_on:
      - backend  # Ensure the backend service starts before the frontend
    networks:
      - app-network  # Use the same network as backend service

networks:
  app-network:
    driver: bridge  # Use a bridge network to connect the backend and frontend services
