apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: simonweigold/kubernetes-demo-frontend:latest
        ports:
        - containerPort: 3000
        env:
          - name: BACKEND_URL
            value: "http://backend-service:5000/api"
