apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nocodb
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      containers:
      - name: nocodb
        image: nocodb/nocodb:latest
        ports:
        - containerPort: 8080
        env:
        - name: NC_DB
          value: "postgres"
        - name: DATABASE_URL
          value: "postgres://postgres:aussicht45%3FINSELI@cold-postgresql-playground.postgres.database.azure.com:5432/nocodb?sslmode=require&ssl=true"
---
apiVersion: v1
kind: Service
metadata:
  name: nocodb-service
spec:
  type: LoadBalancer
  selector:
    app: nocodb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
